language: java
sudo: false
jdk: oraclejdk11
script:
- ./gradlew compileJava
- ./gradlew jar
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - ./**/hpjpc*.jar
  skip_cleanup: true
  on:
    repo: LoyolaChicagoCode/hpjpc-source-java
    tags: true
